#
# AMD-CI temporary test setup:
# - TCP pipe cleaner
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefill
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: default/amd-host-device-nad
    spec:
      hostIPC: true
      containers:
        - name: modelserver
          imagePullPolicy: Always
          resources:
            limits:
              amd.com/gpu: "8"
              amd.com/vnic: "8"
            requests:
              amd.com/gpu: "8"
              amd.com/vnic: "8"
          env:
            - { name: UCX_TLS,                        value: "tcp,self,rocm,shm" }
            - { name: UCX_LOG_LEVEL,                  value: "INFO" }
            - { name: UCX_PROTO_INFO,                 value: "n" }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: default/amd-host-device-nad
    spec:
      hostIPC: true
      containers:
        - name: modelserver
          imagePullPolicy: Always
          resources:
            limits:
              amd.com/gpu: "8"
              amd.com/vnic: "8"
            requests:
              amd.com/gpu: "8"
              amd.com/vnic: "8"
          env:
            - { name: UCX_TLS,                        value: "tcp,self,rocm,shm" }
            - { name: UCX_LOG_LEVEL,                  value: "INFO" }
            - { name: UCX_PROTO_INFO,                 value: "n" }
