multinode: false

modelArtifacts:
  uri: "hf://amd/Llama-3.3-70B-Instruct-FP8-KV"
  size: 100Gi
  authSecretName: "llm-d-hf-token"
  name: "amd/Llama-3.3-70B-Instruct-FP8-KV"
  labels:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "pd-disaggregation"
    llm-d.ai/hardware-variant: "gpu"
    llm-d.ai/accelerator-vendor: "amd"
    llm-d.ai/model: "Llama-3.3-70B-Instruct-FP8-KV"

accelerator:
  type: amd

routing:
  servicePort: 8000
  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.5.0
    connector: nixlv2
    secure: false

decode:
  parallelism:
    tensor: 8
    data: 1
  create: true
  replicas: 1
  extraConfig:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
    - name: "vllm"
      image: ghcr.io/llm-d/llm-d-rocm:v0.5.0
      modelCommand: vllmServe
      args:
        - "--block-size"
        - "128"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
        - "--disable-uvicorn-access-log"
        - '--attention-backend'
        - 'ROCM_ATTN' # only necessary when TP of prefill != decode; upcoming general fix.
        - "--max-model-len"
        - "32000"
      env:
        # UCX Logging and debugging
        #- name: UCX_PROTO_INFO
        #  value: "y"
        #- name: UCX_LOG_LEVEL
        #  value: "info"
        # Customize transport layers ; see docs
        #- name: UCX_TLS
        #  value: "self,sm,rocm,rc"
        # Customize network devices ; see docs
        #- name: UCX_NET_DEVICES
        #  value: "mlx5_0:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_7:1,mlx5_8:1,mlx5_9:1"
        # Customize RDMA GID ; see docs
        #- name: UCX_IB_GID_INDEX
        #  value: "3"
        # Customize KV-transfer traffic class ; see docs
        #- name: UCX_IB_TRAFFIC_CLASS
        #  value: "41"
        - name: VLLM_NIXL_SIDE_CHANNEL_PORT
          value: "5600"
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VLLM_LOGGING_LEVEL
          value: INFO
      ports:
        - containerPort: 8200
          name: vllm
          protocol: TCP
        - containerPort: 5600
          name: nixl
          protocol: TCP
      resources:
        limits:
          memory: 256Gi
          cpu: "16"
          # note: GPU resources get controlled by parallelism + accelerators above
        requests:
          memory: 256Gi
          cpu: "16"
          # note: GPU resources get controlled by parallelism + accelerators above
      securityContext:
        privileged: true
        capabilities:
          add: ["IPC_LOCK", "SYS_PTRACE"]
      mountModelVolume: true
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: torch-compile-cache
          mountPath: /.cache
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: "64Gi"
  - name: torch-compile-cache
    emptyDir: {}

prefill:
  parallelism:
    tensor: 8
    data: 1
  create: true
  replicas: 1
  extraConfig:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"  # prefill vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
    - name: "vllm"
      image: ghcr.io/llm-d/llm-d-rocm:v0.5.0
      modelCommand: vllmServe
      args:
        - "--block-size"
        - "128"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
        - "--disable-uvicorn-access-log"
        - '--attention-backend'
        - 'ROCM_ATTN' # only necessary when TP of prefill != decode; upcoming general fix.
        - "--max-model-len"
        - "32000"
      env:
        # UCX Logging and debugging
        #- name: UCX_PROTO_INFO
        #  value: "y"
        #- name: UCX_LOG_LEVEL
        #  value: "info"
        # Customize transport layers ; see docs
        #- name: UCX_TLS
        #  value: "self,sm,rocm,rc"
        # Customize network devices ; see docs
        #- name: UCX_NET_DEVICES
        #  value: "mlx5_0:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_7:1,mlx5_8:1,mlx5_9:1"
        # Customize RDMA GID ; see docs
        #- name: UCX_IB_GID_INDEX
        #  value: "3"
        # Customize KV-transfer traffic class ; see docs
        #- name: UCX_IB_TRAFFIC_CLASS
        #  value: "41"
        - name: VLLM_NIXL_SIDE_CHANNEL_PORT
          value: "5600"
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VLLM_LOGGING_LEVEL
          value: INFO
      ports:
        - containerPort: 8000
          name: vllm
          protocol: TCP
        - containerPort: 5600
          name: nixl
          protocol: TCP
      resources:
        limits:
          memory: 256Gi
          cpu: "8"
          # note: GPU resources get controlled by parallelism + accelerators above
        requests:
          memory: 256Gi
          cpu: "8"
          # note: GPU resources get controlled by parallelism + accelerators above
      securityContext:
        privileged: true
        capabilities:
          add: ["IPC_LOCK", "SYS_PTRACE"]
      mountModelVolume: true
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: torch-compile-cache
          mountPath: /.cache
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: "64Gi"
  - name: torch-compile-cache
    emptyDir: {}
