apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-amd-ci.yaml
    target:
      group: leaderworkerset.x-k8s.io
      version: v1
      kind: LeaderWorkerSet
  - path: patch-amd-ci-fabric.yaml
    target:
      group: leaderworkerset.x-k8s.io
      version: v1
      kind: LeaderWorkerSet
  - path: patch-amd-ci-sidecar.yaml
    target:
      group: leaderworkerset.x-k8s.io
      version: v1
      kind: LeaderWorkerSet
      name: .*-decode
